name: dev_basic_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  dio: 4.0.1
  json_annotation: 4.3.0
  json_serializable: 6.0.1
  injectable: ^1.5.0
  get_it: 7.2.0
  injectable_generator: 1.5.0
  build_runner: 2.1.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
